### ISSUE TITLE
search for "Barbie girl" fails

### ISSUE THREAD

**Issue by alexdmiller** [djmailhot/BeatTide#79]
Steps to reproduce:

Search for "Barbie gir" in the song search box.

Expected behavior:

Search results containing the query are returned.

Actual behavior: 

No results are loaded. Error code 422 is displayed in the JavaScript console.

**Comment by alexdmiller** [comment]
Now everyone knows I searched for "Barbie girl"... Crap.

**Comment by alexdmiller** [comment]
Here is the error from the logs:

```
2012-03-09T00:12:17+00:00 app[web.1]: ActiveRecord::RecordInvalid (Validation failed: Title can't be blank, Title is too short (minimum is 1 characters)):
2012-03-09T00:12:17+00:00 app[web.1]:   app/models/song.rb:51:in `block in find_or_create'
2012-03-09T00:12:17+00:00 app[web.1]:   app/models/album.rb:22:in `find_or_create'
2012-03-09T00:12:17+00:00 app[web.1]:   app/models/song.rb:44:in `find_or_create'
2012-03-09T00:12:17+00:00 app[web.1]:   app/controllers/grooveshark_controller.rb:40:in `block in songs_from_query'
2012-03-09T00:12:17+00:00 app[web.1]:   app/controllers/grooveshark_controller.rb:39:in `map'
2012-03-09T00:12:17+00:00 app[web.1]:   app/controllers/grooveshark_controller.rb:39:in `songs_from_query'
```

**Comment by bkw7** [comment]
Searching for "rammestein" in music search also has this result.

**Comment by mwinstanley** [comment]
Fixed! Now displays "Unknown Album" and "Unknown Artist" when appropriate. Also shows "No search results" if the query returned no songs.
